added unattend-upgrades to software.pp, the rest perpetrated by unknown

diff --git a/files/usr/local/bin/ring-all b/files/usr/local/bin/ring-all
--- a/files/usr/local/bin/ring-all
+++ b/files/usr/local/bin/ring-all
@@ -1,14 +1,24 @@
 #!/usr/bin/env bash
-if [ $# -ne 1 ]
-then
-    echo -e "No arguments were given\nUsuage: `basename $0` \"command to be executed on all ring servers\""
-    exit 65
+# Written by Job Snijders <job@snijders-it.nl>
+# Modified by Sten Spans <sten@snore.nl>
+
+if [ $# -lt 1 ]; then
+    echo "No arguments were given"
+    echo "Usage: `basename $0` \"command to be executed on all ring servers\""
+    exit 1
 fi
 
-SERVERS=$(dig -t txt +short ring.nlnog.net | sed 's/\"//g')
+SERVERS=$(dig -t txt +short ring.nlnog.net)
+SERVERS=${SERVERS//'"'/}
+
 for host in $SERVERS
 do
-echo "host: $host.ring.nlnog.net"
-ssh -q -t $host.ring.nlnog.net $@ || echo "ERROR: ssh command failed"
-echo ""
+    echo "host: $host.ring.nlnog.net"
+    ssh -q -t $host.ring.nlnog.net $@
+    ret=$?
+    if [ "$ret" = 255 ]; then
+	echo "ERROR: ssh connection failed"
+    elif [ "$ret" != 0 ]; then
+	echo "ERROR: remote command failed"
+    fi
 done
